import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:routina/core/theaming/app_colors.dart';

class HabitConstants {
  static const List<Color> presetColors = [
    AppColors.primary,
    Color(0xFFFF6B6B),
    Color(0xFF4ECDC4),
    Color(0xFFFFBE0B),
    Color(0xFFA663CC),
    Color(0xFFFF9F1C),
    Color(0xFF2EC4B6),
    Color(0xFF6C5CE7),
    Color(0xFF00D2FF),
    Color(0xFF55EFC4),
    Color(0xFFFD79A8),
    Color(0xFFFDCB6E),
    Color(0xFFE17055),
    Color(0xFF74B9FF),
    Color(0xFFA29BFE),
    Color(0xFF00B894),
    Color(0xFFE84393),
    Color(0xFF0984E3),
    Color(0xFF00CEC9),
    Color(0xFFFF4757),
    Color(0xFFFF6348),
    Color(0xFFFF7675),
    Color(0xFFFD79A8),
    Color(0xFFFDCB6E),
    Color(0xFFFFE66D),
    Color(0xFFFFD93D),
    Color(0xFFFED330),
    Color(0xFFFFC312),
    Color(0xFFF39C12),
    Color(0xFFE67E22),
    Color(0xFFD35400),
    Color(0xFFE74C3C),
    Color(0xFFC0392B),
    Color(0xFF1ABC9C),
    Color(0xFF16A085),
    Color(0xFF2ECC71),
    Color(0xFF27AE60),
    Color(0xFF3498DB),
    Color(0xFF2980B9),
    Color(0xFF5DADE2),
    Color(0xFF85C1E2),
    Color(0xFFAED6F1),
    Color(0xFF9B59B6),
    Color(0xFF8E44AD),
    Color(0xFFBB8FCE),
    Color(0xFFD7BDE2),
    Color(0xFFEC7063),
    Color(0xFFE8DAEF),
    Color(0xFFF4D03F),
    Color(0xFFF7DC6F),
    Color(0xFF52BE80),
    Color(0xFF73C6B6),
    Color(0xFF85C1E9),
    Color(0xFF5DADE2),
    Color(0xFF48C9B0),
    Color(0xFF1C2833),
    Color(0xFF34495E),
    Color(0xFF566573),

  ];

  static const Map<String, IconData> iconsMap = {
    'sport': Icons.directions_run_rounded,
    'water': Icons.water_drop_rounded,
    'read': CupertinoIcons.book_fill,
    'sleep': CupertinoIcons.moon_fill,
    'meditate': Icons.self_improvement_rounded,
    'code': Icons.code_rounded,
    'money': Icons.attach_money_rounded,
    'study': Icons.school_rounded,
    'food': Icons.restaurant_rounded,
    'art': Icons.palette_rounded,
    'music': CupertinoIcons.music_note_2,
    'time': Icons.access_time_filled_rounded,
    'journal': Icons.edit_note_rounded,
    'idea': Icons.lightbulb_rounded,
    'game': Icons.sports_esports_rounded,
    'prayer': Icons.mosque_rounded,
    'work': Icons.work_rounded,
    'clean': Icons.cleaning_services_rounded,
    'pet': Icons.pets_rounded,
    'social': Icons.people_rounded,
    'exercise': Icons.fitness_center_rounded,
    'yoga': Icons.self_improvement_rounded,
    'walk': Icons.directions_walk_rounded,
    'bike': Icons.directions_bike_rounded,
    'swim': Icons.pool_rounded,
    'gym': Icons.sports_gymnastics_rounded,
    'coffee': Icons.local_cafe_rounded,
    'tea': Icons.emoji_food_beverage_rounded,
    'vitamin': Icons.medication_rounded,
    'health': Icons.favorite_rounded,
    'doctor': Icons.local_hospital_rounded,
    'therapy': Icons.healing_rounded,
    'mindfulness': Icons.psychology_rounded,
    'gratitude': Icons.favorite_border_rounded,
    'affirmation': Icons.format_quote_rounded,
    'stretch': Icons.accessibility_new_rounded,
    'dance': Icons.music_note_rounded,
    'sing': Icons.mic_rounded,
    'guitar': Icons.piano_rounded,
    'piano': Icons.piano_rounded,
    'write': Icons.create_rounded,
    'blog': Icons.article_rounded,
    'podcast': Icons.headphones_rounded,
    'language': Icons.language_rounded,
    'course': Icons.menu_book_rounded,
    'skill': Icons.build_rounded,
    'project': Icons.folder_rounded,
    'meeting': Icons.groups_rounded,
    'call': Icons.phone_rounded,
    'email': Icons.email_rounded,
    'social_media': Icons.share_rounded,
    'family': Icons.family_restroom_rounded,
    'friend': Icons.person_add_rounded,
    'date': Icons.favorite_rounded,
    'cooking': Icons.restaurant_menu_rounded,
    'baking': Icons.cake_rounded,
    'grocery': Icons.shopping_cart_rounded,
    'budget': Icons.account_balance_wallet_rounded,
    'save': Icons.savings_rounded,
    'invest': Icons.trending_up_rounded,
    'garden': Icons.local_florist_rounded,
    'plant': Icons.eco_rounded,
    'nature': Icons.park_rounded,
    'photography': Icons.camera_alt_rounded,
    'video': Icons.videocam_rounded,
    'draw': Icons.brush_rounded,
    'paint': Icons.format_paint_rounded,
    'craft': Icons.build_circle_rounded,
    'organize': Icons.inventory_2_rounded,
    'declutter': Icons.delete_outline_rounded,
    'laundry': Icons.local_laundry_service_rounded,
    'shopping': Icons.shopping_bag_rounded,
    'car': Icons.directions_car_rounded,
    'commute': Icons.train_rounded,
    'travel': Icons.flight_rounded,
    'explore': Icons.explore_rounded,
    'adventure': Icons.terrain_rounded,
    'hiking': Icons.landscape_rounded,
    'camping': Icons.cabin_rounded,
    'beach': Icons.beach_access_rounded,
    'sunset': Icons.wb_twilight_rounded,
    'sunrise': Icons.wb_sunny_rounded,
    'weather': Icons.wb_cloudy_rounded,
    'star': Icons.star_rounded,
    'moon': CupertinoIcons.moon_stars_fill,
    'sun': Icons.wb_sunny_rounded,
    'cloud': Icons.cloud_rounded,
    'rain': Icons.grain_rounded,
    'snow': Icons.ac_unit_rounded,
  };

  static IconData getIcon(String key) {
    return iconsMap[key] ?? Icons.circle;
  }
}
