// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNcnMRsp2IgNxENUb9gKdMK9TGqwJv5Vs',
    appId: '1:370947315001:web:2eb7ab4e9590e6052804e8',
    messagingSenderId: '370947315001',
    projectId: 'my-routina-app',
    authDomain: 'my-routina-app.firebaseapp.com',
    storageBucket: 'my-routina-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9O5VU8fTPeTlOeyotcOlJ03x_gtAC03w',
    appId: '1:370947315001:android:3d3798113ba9b8ce2804e8',
    messagingSenderId: '370947315001',
    projectId: 'my-routina-app',
    storageBucket: 'my-routina-app.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC17ba45gNMJPIHRtwbCJidEZw5zx-KzMc',
    appId: '1:370947315001:ios:a5e8e2627f1b02de2804e8',
    messagingSenderId: '370947315001',
    projectId: 'my-routina-app',
    storageBucket: 'my-routina-app.firebasestorage.app',
    iosBundleId: 'com.example.routina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC17ba45gNMJPIHRtwbCJidEZw5zx-KzMc',
    appId: '1:370947315001:ios:a5e8e2627f1b02de2804e8',
    messagingSenderId: '370947315001',
    projectId: 'my-routina-app',
    storageBucket: 'my-routina-app.firebasestorage.app',
    iosBundleId: 'com.example.routina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNcnMRsp2IgNxENUb9gKdMK9TGqwJv5Vs',
    appId: '1:370947315001:web:7afa4b8a488bef272804e8',
    messagingSenderId: '370947315001',
    projectId: 'my-routina-app',
    authDomain: 'my-routina-app.firebaseapp.com',
    storageBucket: 'my-routina-app.firebasestorage.app',
  );

}